################################################################################
#
# Build script for project
#
###############################################################################

# Add source files here
EXECUTABLE	:= Analyze_Cluster	
SOURCE := Analyze.cpp

all:
	g++ -o $(EXECUTABLE) -g  $(SOURCE)

clean:
	rm $(EXECUTABLE)

